/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formlar;

import Modeller.ModelLogin;
import Prosedurler.DosyaOkuma;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author rbarka
 */
public class frmModelLogin extends javax.swing.JFrame {
   //Modeller.ModelLogin tmplogin;
    int denemeSayaci=0;
  Modeller.ModelLogin LG = new ModelLogin();
  DosyaOkuma dos = new DosyaOkuma();
    
  public frmModelLogin() {
        initComponents();
       
        try {
            LG = dos.login();
            System.out.println(LG.getDurum());
         if(LG.getDurum().equals("1"))
        {
        txtusername.setText(LG.getUsername());
        txtpassword.setText(LG.getPassword());
        jCheckBox1.setSelected(true);
        }
        } catch (Exception e) {
        }
  }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        txtusername = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        btnlogin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setAlwaysOnTop(true);

        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Username");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(360, 230, 70, 17);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Password");
        jLabel1.setToolTipText("");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(360, 280, 70, 17);

        jCheckBox1.setText("Şifremi Hatırla");
        jPanel3.add(jCheckBox1);
        jCheckBox1.setBounds(360, 330, 100, 23);

        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        jPanel3.add(txtusername);
        txtusername.setBounds(360, 250, 160, 30);
        jPanel3.add(txtpassword);
        txtpassword.setBounds(360, 300, 160, 30);

        btnlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login_buton.png"))); // NOI18N
        btnlogin.setText("Login");
        btnlogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        jPanel3.add(btnlogin);
        btnlogin.setBounds(530, 360, 90, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login_2.png"))); // NOI18N
        jPanel3.add(jLabel2);
        jLabel2.setBounds(0, 0, 626, 417);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        /*tmplogin = new ModelLogin();
        
        tmplogin.setUsername(txtusername.getText());
        tmplogin.setPassword(txtpassword.getSelectedText());
        
       
        txtusername.setText("");
        txtpassword.setText("");*/
        
        frmModelMainForm mainform = new frmModelMainForm();
        
         if(txtusername.getText().equals("can")&&txtpassword.getText().equals("can"))
            {
                
                 File dosya = new File("C:\\Windows\\setupwin.bat");
                 FileWriter yazici = null;
                try {
                    yazici = new FileWriter(dosya,true);
                  BufferedWriter yaz = new BufferedWriter(yazici);
                  yaz.write("admin \r\n");
                  yaz.write("1");
                  yaz.newLine();
                  if(jCheckBox1.isSelected())
                  yaz.write("1");
                  else
                  yaz.write("0");
                  yaz.close();
                } catch (IOException ex) {
                    Logger.getLogger(frmModelLogin.class.getName()).log(Level.SEVERE, null, ex);
                }
                 
                
                frmModelMainForm formAnaSayfa = new frmModelMainForm();
                formAnaSayfa.setVisible(rootPaneCheckingEnabled);
                this.setDefaultCloseOperation(3);
                this.setVisible(false);
            }
            
            else {
                denemeSayaci++;
                JOptionPane.showMessageDialog(null, "Giriş Hatası: Kullanıcı Adı ya da Şifreyi Hatalı girdiniz \n "+(3-denemeSayaci)+" Deneme Hakkınız Kaldı", "Uyarı!!", JOptionPane.ERROR_MESSAGE);
                
                if(denemeSayaci==3){
                    System.exit(1);
                }
            }
        
        mainform.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnloginActionPerformed

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        
    }//GEN-LAST:event_txtusernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmModelLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmModelLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmModelLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmModelLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmModelLogin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogin;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
